package com.sendmefile77.gamebroth.ai

/** Small Android-free guard used before generated bytes are written to the gallery. */
internal object PngPayload {
    private val signature = byteArrayOf(
        0x89.toByte(), 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a,
    )

    fun isPng(bytes: ByteArray): Boolean {
        if (bytes.size < signature.size + 12) return false
        if (!signature.indices.all { bytes[it] == signature[it] }) return false
        val typeOffset = bytes.size - 8
        return bytes[typeOffset] == 'I'.code.toByte() &&
            bytes[typeOffset + 1] == 'E'.code.toByte() &&
            bytes[typeOffset + 2] == 'N'.code.toByte() &&
            bytes[typeOffset + 3] == 'D'.code.toByte()
    }
}
